export { default as Terminal } from "./Terminal.jsx";
export { default as Safari } from "./Safari.jsx";
export { default as Finder } from "./Finder.jsx";
export { default as TextFile } from "./TextFile.jsx";
export { default as ImageFile } from "./ImageFile.jsx";
export { default as Resume } from "./Resume.jsx";
export { default as Photos } from "./Photos.jsx";
export { default as Contact } from "./Contact.jsx";
export { default as Trash } from "./Trash.jsx";
